output_dir: ~/scratch/torchglycan_output/

dataset:
  class: ProteinGlycanInteraction
  path: ~/scratch/glycan-datasets/
  view: atom-glycan
  unit_feature: default
  link_feature: default
  atom_feature_glycan: symbol
  bond_feature_glycan: symbol
  atom_feature: null              # for Protein
  bond_feature: null              # for Protein

task:
  class: GlycanProteinInteraction
  model:
    class: GlycanProteinAttention
    glycan_model:
      class: GlycanAA
      num_unit: 210
      num_relation: 89
      input_dim: 128
      hidden_dims: [128, 128, 128]
      concat_hidden: True
      batch_norm: True
      activation: gelu
      readout: dual
    protein_cache_path: cache/protein_embeddings.pt
    dropout: 0.1
    heads: 8
    dim_head: 64
  criterion: mse
  metric: [ "mae", "rmse", "spearmanr" ]

metric: root mean squared error [interaction]

optimizer:
  class: Adam
  lr: 5.0e-4
  weight_decay: 0.001

engine:
  gpus: {{ gpus }}
  batch_size: 32

train:
  num_epoch: 10

model_checkpoint: {{ ckpt }}
load_unsupervised: True
